name: Gunluk Finans Raporu Gonder

on:
  workflow_dispatch: # Manuel olarak çalıştırma butonu ekler
  schedule:
    # Her gün Türkiye saati ile sabah 09:00'da çalışır (UTC 06:00)
    - cron: '11 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python Ortamını Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Paketleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install yfinance

      - name: Rapor Scriptini Çalıştır
        env:
          GMAIL_KULLANICI_ADI: ${{ secrets.GMAIL_KULLANICI_ADI }}
          GMAIL_UYGULAMA_SIFRESI: ${{ secrets.GMAIL_UYGULAMA_SIFRESI }}
        run: python finans_raporu.py
