name: Gunluk Finans Raporu Gonder

on:
  workflow_dispatch:
  schedule:
    - cron: '00 13 * * **'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3
      - name: Python Ortamını Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Gerekli Paketleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install yfinance sendgrid
      - name: Rapor Scriptini Çalıştır
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          GMAIL_KULLANICI_ADI: "furkanbalkac@gmail.com" # Buraya doğrulanmış gönderici adresinizi yazın
        run: python finans_raporu.py
